config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists do
    resources :artists
  end

  resources :artists do
    resources :songs
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :artists, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_list
  before_actio :set_artist, only: (:show, :edit, :update, :destroy)
  
  def index
    @artists = List.where("list_id = ?"params[:list_id])
  end

  def show
  end

  def new
    @artist = @list.artists.new
  end

  def edit
  end

def create
  @artist = @list.artists.new(artist_params)
  
    if @artist.save
      redirect_to [:@list, @artist]
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@list, @artist]
    else
      render :edit
    end
  end


def destroy
  @artist.destroy
  redirect_to list_artist_path
end


private

  def set_list
    @list = List.find[:list_id]
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :song)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :update, :edit, :destroy]
  
  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list =List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
    render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    reiderct_to lists_path
  end


  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:artist, :song)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  
  def new
    @song = Song.where("artist_id = ?" params[:artist_id])
  end

  def create
    @song = @artist.song.new(song_params)
    if @song.save
      redirect_to list_artis_path(@artist.list_id, @artist)
    else
      render :new
    end
  end


  private
  
  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def songs_params
    params.require(:song).permit(:name, @artist)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist?' : 'Create Artist?' %></h1>
<hr />
<%= form_with(model: [@list, @artist], local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :song %>
  <%= f.text_field :song, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button blue" %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form", list: @list, artist: @artist %>

<%= link_to "Back", list_artists_path(@list) %>

app/views/artists/index.html.erb
<h1>Click the Artist to view</h1>
<%= link_to 'Add Artist', new_list_artist_path(@list) %>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, [@list, @artist] %></li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render "form", list: @list, artist: @artist %>
<%= link_to "back", lists_artists_path(@list) %>

app/views/artists/show.html.erb
<h1><%= @artist.name </h1>
<h1><%= @list.name %></h1>
<h4>Name: <%= @artist.name %></h4>
<h4>Species: <%= @artist.species %></h4>
<h4>Age: <%= @artist.age %></h4>
<br />
<h2>Songs</h2>
<% @artist.congs.each do |song| %>
  <%= render 'songs/song', { song: song } %>
<% end %>
<br />
<%= link_to 'Add Song', new_artist_song_path(@artist), class: "ui button blue" %>
<br />
<br />
<%= link_to 'Edit Artist', edit_list_artist_path([@list, @artist]), class: "ui button invert blue" %> |
<%= link_to 'Delete Artist', [@list, @artist], method: :delete, class: "ui button invert red" %> |
<%= link_to 'Back To Artists', list_artists_path(@list), class: "ui button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
  </head>

  <div class="ui container">
    <%= yield %>
  </div>
</html>

app/views/lists/_form.html.erb
<%= form_with(model:list, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
<%= end %>

app/views/lists/edit.html.erb
<h1>Edit lists/h1>

<%= render "form", list: @list %>

<%= link_to "Show", list_path(@list) %>
<%= link_to "Back", lists_path %>

app/views/lists/index.html.erb
<h1 class="ui header">All Lists</h1>
<% @lists.each do |list| %>
  <h1><%= list.name %></h1>
  <%= link_to "Show", list_path(list) %>
  <%= link_to "Edit", edit_list_path(list) %>
  <%= link_to "Destroy", list_path(list), method: :delete %>
<% end %>
<br />
<%= link_to "New list", new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>
<%= render "form", list: @list %>

<%= link_to "back" new_list_artist_path %>

app/views/lists/show.html.erb
<div class="ui card">
  <div class="content">
    <p class="header">
      <%= @list.name %> <%= @list.name %>
    </p>
  </div>
  <div class="extra content">
    <%= link_to 'Edit', edit_list_path?(@list) %>  
    <%= link_to 'Back', lists_path %>
  </div>
</div>  

app/views/songs/new.html.erb
<h1>Add a Song</h1>
<%= form_with(model: [@artist, @song], local: true, class: "ui form") do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name, required: true %>
  <br />
  <%= f.label :artist %>
  <%= f.text_field :artist, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "ui button blue" %>
<% end %>